### ISSUE TITLE
Device not supported

### ISSUE THREAD

**Issue by MrKinauJr** [LoreBadTime/Bluetooth-HID-Enabler#1]
Hello, today i tried enabling the HID Profiles but it did not succeed. I have a OnePlus 9 Pro (LE2123). It has Android 11.

If you want to support it lmk what you need.

**Comment by LorVC** [comment]
Hi there,you need to tell me if there is this file in this location /system/vendor/overlay/BluetoothHIDEnabler/BluetoothHIDEnabler.apk after you boot the device with the module installed and enabled
If it's present the file,then i suggest to change your ROM to a lineageOS ROM,other said specifically on OnePlus devices that they got the same problem,and they preferred to change the rom.
Else I'll try to investigate

**Comment by MrKinauJr** [comment]
It's there but sadly i cannot switch to another rom since there aren't any since the device is kinda new.  I guess I have to wait.

**Comment by LorVC** [comment]
Sorry dude...i can't help,my module enables it on devices that have it disabled by default, I'm not able to implement it fully

**Comment by LoreBadTime** [comment]
I will update the readme
