### ISSUE TITLE
Any chance of updating for Magisk 23.0?

### ISSUE THREAD

**Issue by carboniris** [LoreBadTime/Bluetooth-HID-Enabler#2]
Tried to use this as of November 2021, seems to not work.

**Comment by LorVC** [comment]
Hi there,i need few feedbacks before updating(since I'm still in android 10)
1) Android version.
2) after installing the module,if you open this folder can you see this apk "BluetoothHIDEnabler.apk"?system/vendor/overlay/BluetoothHIDEnabler/
3) the module worked with older magisk(21.4/22.0)?

**Comment by carboniris** [comment]
1. Android 10, Resurrection Remix
2. With Magisk and this module (as well as a few others) installed, there is no /system/vendor/overlay folder
3. I haven't used earlier versions of Magisk

**Comment by LorVC** [comment]
Ok on Android 10 with magisk 23 it's working fine on my phone,so you said that there isn't any folder or file in /system/vendor/overlay (even external files)?

**Comment by LorVC** [comment]
Maybe resurrection remix doesn't need that folder due other types of personalization.However android it's always the same,so folders should be scanned in the same way,can you try creating that folder if isn't present? and then reinstalling the module?
EDIT:PLEASE BE CAREFUL OF WHAT YOU ARE DOING,DO A BACKUP

**Comment by carboniris** [comment]
Yep! creating /system/vendor/overlay and then reinstalling the module fixed it

**Comment by LorVC** [comment]
Strange,but guess I was thinking good lmao
