### ISSUE TITLE
Bluetooth not working after installing module

### ISSUE THREAD

**Issue by Voxybuns** [LoreBadTime/Bluetooth-HID-Enabler#3]
I'm running LineageOS 18.1 (based on Android 11) on my OnePlus 3T. I tried installing this module with Magisk 23.0, but I keep running into issues.

At first, it took out all the wireless stuff. No SIM unlock prompt on startup, no Wi-Fi, nothing. It's like it locked itself into some kind of airplane mode. Reading through the solved issues, I realized I had no "overlay" folder in my /system/vendor directory, so I created it and tried again.

This time, it's connecting to my carrier and Wi-Fi's working again, but Bluetooth is still not working. It'll try turning on for a few seconds before turning back off. Is there anything I can do?

**Comment by LorVC** [comment]
I searched your phone,i think this is a hardware/software issue,the module works because google from Android 9 forced the hid compatibility so the phones from that generation have a forced newer hardware, however as i found your phone comes from Android 6.0.1,so this is like a incompatibility issue

**Comment by LorVC** [comment]
I could investigate further,but I don't think I will be able to fix it.You need to tell me if after the module installation it's present the /system/vendor/overlay/BluetoothEnabler folder

**Comment by Voxybuns** [comment]
Very sorry for the late reply, I thought I'd get the notification on GitHub but it got buried in my inbox instead. :/

Anyway, I eventually switched to a different ROM (PixelExperience instead of LineageOS) and... it worked flawlessly after it, for some reason, so it must've been something specific to the LineageOS build I was using.
